name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.CAMPUSKEY }}

    - name: List SSH keys
      run: ssh-add -l

    - name: Add server to known_hosts
      run: ssh-keyscan -H -v -p 44973 *** >> ~/.ssh/known_hosts


    - name: Print known_hosts
      run: cat ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}   << 'EOF'
          set -e
          cd /home/${{ secrets.DEPLOY_USER }}/backend
          git fetch origin main
          git reset --hard origin/main
          sudo systemctl restart mapbackend.service
        EOF
